### ISSUE TITLE
Request ability to run via command line call

### ISSUE THREAD

**Issue by Digimont** [LukeCroteau/RaidExtractor#12]
Could you please create the ability to call the Raid Extractor from another program, bypassing the user interface? Perhaps a simple parameter passed in the call that runs the extraction, saves to a static filename in the current directory, replacing an existing file without prompts.

**Comment by achampto** [comment]
The pull request I just submitted #30 separates the core logic out so that it can be become a nuget package and consumed that way. I'm messing around building a separate command line app to manipulate the data so being able to consume the data directly instead of having to run this tool then ingest the output json is definitely a benefit. This should also lend itself to having a CLI put in front of it easily

**Comment by LukeCroteau** [comment]
@Digimont
Please check Release v0.8.19.
Thanks to @achampto I was easily able to add a console version of the program.
I dislike having 2 different versions, but it saved me a little bit of popping around code for the moment. (My current stashes are already a nightmare thanks to the refactoring, but it's worth it in the end!)

**Comment by Digimont** [comment]
Worked perfectly and seamlessly at the 2nd attempt.
1st attempt I ran it by providing a path to the exe and just the --nogui parameter. The artifacts.json was not created in the same directory as the exe, it was created in my libraries/documents folder. 2nd attempt I specified path and filename for the output, all good!
I don't consider that a bug/issue, just thought you should know.
Also, pleasantly surprised I did not have to add any code at all for checking if it had finished before I opened the json for reading. Programmatic control doesn't return to VBA until the process is complete
