### ISSUE TITLE
Great Hall and Arena Level required to accurately calculate Champions stats

### ISSUE THREAD

**Issue by Digimont** [LukeCroteau/RaidExtractor#21]
We have the Champions stats, and the artifacts stats, but great hall and arena level need to be extracted to be able to complete the calculation. Is this possible? I'd assume it would need either it's own JSON or be additional arrays in the existing one. My preference would be a separate JSON & request, as pulling just that from the game should be pretty fast.

**Comment by F0RM4TION** [comment]
Pretty sure HH’s version takes great hall and arena stats so it should be possible, personally I’d prefer it just to be added to the existing format since I’m converting it all to .csv and then separating the coloumns. Either way since it’s only afew stats that don’t change very often I’m not too annoyed by manually adding the stats myself. Would be nice if it could be added tho. 👍

**Comment by Digimont** [comment]
The HH version does get these stats, I should have mentioned that. Arena level can change regularly, especially at the beginning of the week, when everyone resets back to the start of the level. Perhaps what I hope to do with it is a bit more "live" than your use, but to be honest, I'll take it whatever way it comes, and with gratitude. Having 90
% of the data required to provide what an end user would want to see...is kind of frustrating!

**Comment by LukeCroteau** [comment]
I'm actively working on this right now. It will be added to the artifacts.json output.

**Comment by Digimont** [comment]
Sorry for asking Luke...do you envisage this being in the near or distant future? I can cope with whatever the timing is..just trying to make decisions on what to do next in my own project.

**Comment by LukeCroteau** [comment]
> Sorry for asking Luke...do you envisage this being in the near or distant future? I can cope with whatever the timing is..just trying to make decisions on what to do next in my own project.

@Digimont So this is a fair question.
The answer is... i'm not sure?
I started a new job a few weeks ago, and I've been acclimating. I've tried to keep everything up to date, with the exception of the Hero JSON file (as I haven't built a parser for it yet).

My plan is to get back to it in a week or two and continue on with some of the pending issues, and some of the enhancements, this included. I'm not sure how well it'll pan out, but I already have the structures and know where to find most of the information.

**Comment by Digimont** [comment]
All good. Congratulations of the new job! Real life always takes precedence over gaming.

**Comment by zerfl** [comment]
I have implemented the arena league extraction in https://github.com/zerfl/RaidExtractor/commit/4c90b1097be553783a6bcedff041277285966464.  However, it's simply the raw data, no extra calculations are done. A general question is how should this be handled by the extractor? Should the formula be adapted to include arena/great hall, or is this something the end user does themselves in their application?
As for the great hall extraction, the structure and offset is clear to me, just haven't found the time to implement it yet.

**Comment by LukeCroteau** [comment]
It's my opinion that we should do as few calculations as possible, and let other people make/use tools that provide more complete data.

Otherwise, someone who is (for example) trying to model a Theoretical team would have to first do the math to Undo the Great Hall and Arena bonuses, then apply new bonuses (Lets say they plan on hitting Gold 4, instead of sitting in Gold 3 like they are now).

If we let those datum just be separate pieces in the extract, it's much easier for tools to allow modeling for other scenarios.

**Comment by Digimont** [comment]
Just seen! Great stuff. As soon as I finish the bit of code I have open, I'll jump on in.

Regards

Dave
