### ISSUE TITLE
Could anyone help me gather what is needed for debugging this in VSCode? I was hoping to use it as a learning project

### ISSUE THREAD

**Issue by newalias34** [LukeCroteau/RaidExtractor#38]
I've been unable to properly launch the project in VSCode and I'm not sure what requirements, or possibly actions from me are missing. I cloned the project into VSCode, then tried to debug it right away and it wouldn't proceed since it was requesting .NET framework 3.1.0. I installed that and also .NET Framework 4.8 after realizing I didn't have that either.

That's basically as far as I got, since now when I start debugging I don't receive errors and if I step through the code it continues until I'm left with just the debug console giving me this message:

Microsoft.Hosting.Lifetime: Information: Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
Microsoft.Hosting.Lifetime: Information: Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
Microsoft.Hosting.Lifetime: Information: Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\bryan\Documents\Projects\RaidExtractor-master\Website
Microsoft.Hosting.Lifetime: Information: Content root path: C:\Users\bryan\Documents\Projects\RaidExtractor-master\Website

I expected to see the little window appear at some point with the option to save JSON but it never appears. I've launched Raid after the program is listening, as well as before but it doesn't seem to work either way around.

Could anyone shed some light on what I need to do to get it running in debug mode so I can step through the code? Any advice appreciated, thanks!

**Comment by LukeCroteau** [comment]
@newalias34 
It sounds to me like you've loaded the Website project, and not the Extractor EXE.
Which project were you trying to debug?
If you were trying to debug the EXE, you'd want to switch your Loading profile to be runing the RaidExtractor.csproj instead of the Website.csproj

I don't use VSCode for .Net code with Winforms, so i'm not sure quite what you'd need to do to hook that up.

The Extractor is much more suited to be run and debugged in Visual Studio proper.
The Website could easily be debugged in VSCode. That's what I've used to debug it.

**Comment by newalias34** [comment]
@LukeCroteau 
I ended up installing the full visual studio and then running it through that where it worked just fine, thanks for the tip.
